version: "3.5"

networks:
  localdev:
    name: localdev

services:
  main-api:
    build: StandardApi/
    restart: always
    ports:
      - "1987:80"
    depends_on:
      - db-server
    networks:
      - localdev
    #environment:
      #- ConnectionStrings__0__DefaultConnection='Server=db-server;Database=StandardApi;User=sa;Password=ZakariaBoukhris@1987!'
  
  db-server:
    image: microsoft/mssql-server-linux:2017-latest
    container_name: db-server
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=ZakariaBoukhris@1987!
      - MSSQL_TCP_PORT=1433
    ports:
      - "1400:1433"
    networks:
      - localdev
